POST http://localhost:8080/products/
Content-Type: application/json

{
    "name": "Product A",
    "description": "Description of Product A",
    "price": 10000
}

###
GET http://localhost:8080/products/

###
GET http://localhost:8080/products/1

###
PUT http://localhost:8080/products/1
Content-Type: application/json

{
    "name": "Updated Product A",
    "description": "Updated Description",
    "price": 12000
}

###
DELETE http://localhost:8080/products/1
